### ISSUE TITLE
`xdem.DEM(..., load_data=False)` is not working

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#164]
Example:
```python
>>> import xdem
>>> xdem.DEM(xdem.examples.get_path("longyearbyen_ref_dem"))
No metadata could be read from filename.
>>> xdem.DEM(xdem.examples.get_path("longyearbyen_ref_dem"), load_data=False)
No metadata could be read from filename.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/erik/Projects/ETH/xdem/xdem/dem.py", line 75, in __init__
    if self.nbands > 1:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

@rhugonnet, any ideas?

**Comment by rhugonnet** [comment]
Right now we only accept a `Raster` or `SatelliteImage` with `self.nbands == 1`.
To accept unloaded data, we should also accept `self.nbands` as `None`, and modify in `DEM.__init__()`:
```python
 if self.nbands > 1:
            raise ValueError('DEM rasters should be composed of one band only')
```
into
```python
 if self.nbands is not None and self.nbands > 1:
            raise ValueError('DEM rasters should be composed of one band only')
```
Right now we don't use `nbands` anywhere else in `DEM`, so the rest should work OK
